watson:
  nlc:
    jp:
      classifier_id: "INPUT settings.local.yml"
      user: "INPUT settings.local.yml"
      password: "INPUT settings.local.yml"
    en:
      classifier_id: "INPUT settings.local.yml"
      user: "INPUT settings.local.yml"
      password: "INPUT settings.local.yml"
